# Generated by Django 5.2.3 on 2025-06-30 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0002_rename_category_catagory_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
