# Generated by Django 5.2.3 on 2025-07-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0003_rename_catagory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=50),
        ),
    ]
