# Generated by Django 5.2.3 on 2025-07-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0006_alter_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
