# Generated by Django 5.2.3 on 2025-07-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0008_rename_category_name_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_name',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
