# Generated by Django 5.2.3 on 2025-07-05 13:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0009_product_detail_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ship_from',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
