# Generated by Django 6.0.4 on 2026-04-16 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0015_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='status',
        ),
        migrations.RemoveField(
            model_name='category',
            name='trending',
        ),
    ]
