# Generated by Django 5.2.3 on 2025-06-30 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='category',
            new_name='catagory',
        ),
    ]
