# Generated by Django 5.2.3 on 2025-07-01 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0004_alter_products_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
