# Generated by Django 5.2.3 on 2025-07-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_quantity',
            new_name='product_qty',
        ),
    ]
