# Generated by Django 6.0.4 on 2026-04-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0017_alter_product_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail_name',
            field=models.CharField(max_length=3000),
        ),
    ]
