# Generated by Django 6.0.4 on 2026-04-16 18:33

import Ecommerce_site.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0019_alter_product_description_alter_product_detail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=False, upload_to=Ecommerce_site.models.getFileName),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default=False, upload_to=Ecommerce_site.models.getFileName),
        ),
    ]
