# Generated by Django 6.0.4 on 2026-04-16 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_site', '0020_alter_category_image_alter_product_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Catagory',
        ),
    ]
